# Generated by Django 5.2.1 on 2025-06-08 02:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0004_alter_coursereview_options_alter_runhistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='coursereview',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='runhistory',
            options={'ordering': ['-date', '-start_time']},
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='coursereview',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='matchpreference',
            name='preferred_distance',
        ),
        migrations.RemoveField(
            model_name='runhistory',
            name='averageSpeedKmh',
        ),
        migrations.RemoveField(
            model_name='runhistory',
            name='cadenceSpm',
        ),
        migrations.RemoveField(
            model_name='runhistory',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='runhistory',
            name='dateTime',
        ),
        migrations.RemoveField(
            model_name='runhistory',
            name='distanceKm',
        ),
        migrations.RemoveField(
            model_name='runhistory',
            name='elapsedTime',
        ),
        migrations.RemoveField(
            model_name='runhistory',
            name='route',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='title',
            field=models.CharField(default='러닝 채팅방', max_length=100),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='end_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='end_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='start_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='start_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 8)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchpreference',
            name='preferred_distance_range',
            field=models.CharField(choices=[('3-5', '3~5km'), ('5-7', '5~7km'), ('7-10', '7~10km'), ('10+', '10km 이상')], default='5-7', max_length=10),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='cadence',
            field=models.IntegerField(default=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runhistory',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 8)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runhistory',
            name='distance_km',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runhistory',
            name='duration_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runhistory',
            name='heart_rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runhistory',
            name='start_time',
            field=models.TimeField(default=datetime.time(2, 44, 34, 851327)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatroomparticipant',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='kakaoapi.chatroom'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='polyline_points',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.CreateModel(
            name='FriendChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakaoapi.friendchatroom')),
            ],
        ),
        migrations.CreateModel(
            name='MatchQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('preferred_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='any', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mate_reports_made', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakaoapi.chatroom')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mate_reports_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakaoapi.friendchatroom')),
            ],
            options={
                'unique_together': {('chat_room', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
