# Generated by Django 5.2.1 on 2025-06-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0005_friendchatroom_alter_coursereview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursereview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='runhistory',
            options={'ordering': ['-dateTime']},
        ),
        migrations.RenameField(
            model_name='courseinfo',
            old_name='end_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='courseinfo',
            old_name='end_lon',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='start_lat',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='start_lon',
        ),
        migrations.RemoveField(
            model_name='coursereview',
            name='date',
        ),
        migrations.RemoveField(
            model_name='runhistory',
            name='cadence',
        ),
        migrations.RemoveField(
            model_name='runhistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='runhistory',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='runhistory',
            name='duration_min',
        ),
        migrations.RemoveField(
            model_name='runhistory',
            name='start_time',
        ),
        migrations.AddField(
            model_name='coursereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='averageSpeedKmh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='cadenceSpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='distanceKm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='elapsedTime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='fatigue_index',
            field=models.FloatField(blank=True, help_text='피로도 추정치', null=True),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='gap_days',
            field=models.IntegerField(blank=True, help_text='이전 러닝과의 간격 일 수', null=True),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='is_challenge',
            field=models.BooleanField(default=False, help_text='챌린지 참여 여부'),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='pace',
            field=models.FloatField(default=6.0, help_text='분/km'),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='predicted_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='predicted_intensity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='route',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='run_type',
            field=models.CharField(blank=True, choices=[('LSD', 'LSD'), ('Tempo', 'Tempo'), ('Interval', 'Interval'), ('Recovery', 'Recovery')], help_text='러닝 유형 (Optional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='polyline_points',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='runhistory',
            name='heart_rate',
            field=models.IntegerField(blank=True, help_text='평균 심박수 (bpm)', null=True),
        ),
    ]
