# Generated by Django 5.2 on 2025-06-02 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0005_friendchatroom_friendchatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('preferred_distance', models.FloatField()),
                ('preferred_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='any', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
