# Generated by Django 5.2 on 2025-06-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0006_matchqueue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchpreference',
            name='preferred_distance',
        ),
        migrations.RemoveField(
            model_name='matchqueue',
            name='preferred_distance',
        ),
        migrations.AddField(
            model_name='matchpreference',
            name='preferred_distance_range',
            field=models.CharField(choices=[('3-5', '3~5km'), ('5-7', '5~7km'), ('7-10', '7~10km'), ('10+', '10km 이상')], default='5-7', max_length=10),
        ),
    ]
