# Generated by Django 5.2 on 2025-06-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0007_remove_matchpreference_preferred_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchqueue',
            name='preferred_distance',
            field=models.CharField(choices=[('3-5', '3~5km'), ('5-7', '5~7km'), ('7-10', '7~10km'), ('10+', '10km 이상')], default='5-7', max_length=10),
        ),
    ]
