# Generated by Django 5.2 on 2025-06-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0008_matchqueue_preferred_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchqueue',
            name='preferred_distance',
        ),
    ]
