# Generated by Django 5.2 on 2025-06-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0009_remove_matchqueue_preferred_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='title',
            field=models.CharField(default='러닝 채팅방', max_length=100),
        ),
    ]
