# Generated by Django 5.2 on 2025-06-05 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0011_alter_chatroomparticipant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomparticipant',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='kakaoapi.chatroom'),
        ),
        migrations.AlterField(
            model_name='chatroomparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
