# Generated by Django 5.2 on 2025-06-06 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0012_alter_chatroomparticipant_chat_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mate_reports_made', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakaoapi.chatroom')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mate_reports_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
